---
--- Generated by Luanalysis
--- Created by xianyu
--- DateTime: 2023/6/7 14:23
---
--比较线程标识与锁中的标识是否一致
if(redis.call('get',KEYS[1])==ARGV[1]) then
    --释放锁 del key
    return redis.call('del',KEYS[1])
end
return 0